# Generated by Django 3.2 on 2021-04-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espotifai_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
    ]
