# Generated by Django 3.2 on 2021-05-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espotifai_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
        migrations.AlterField(
            model_name='track',
            name='times_played',
            field=models.IntegerField(default=0),
        ),
    ]
